version: '3.8'
services:
  app:
    image: microservice-java:latest
    container_name: microservice-java
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - shared_network

networks:
  shared_network:
    external: true